##################### MIROpt user configuration file ##########################

## NOTE: tabs are not recognized in Yaml format and will trigger an error at
# read-time. Use only spaces to indent content ##

## NOTE: the "-" symbol in the syntax means one entry in a list. For example,
# it's possible to have a list of "Beams" where the "key" in the yaml "key:value"
# structure is void. ##

###############################################################################


# Datapath
Data:
  folder: D:\programs\openREGGUI\REGGUI_userdata\water_data\water15     # Location of your datafiles
  CT: water15_0001.dcm                            # CT slice name to load the 3D image
  RTStruct: rtstructs_50_50_50.dcm             # RT Struct name of file holding the associated contours


# Plan parameters--------------------------------------------------------------
Plan:
  output_path: D:\programs\openREGGUI\REGGUI_userdata\water_data\50_50_50         # If commented out, everything is written in inside the Data.folder/miropt_Plan.name folder
  #PlanExistentFile: D:\programs\openREGGUI\REGGUI_userdata\water_data\50_50_50    # If you already have pre-calculated beamlets, set the path here. The "output_path" variable needs to be commented out. To calculate from scratch comment out this line and re-enable "output_path".
  ScannerDirectory: default   # Default value. Go to MCsquare/Scanners to check what are the other scanners implemented
  MaterialsDirectory: D:\programs\openREGGUI\REGGUI\plugins\openMCsquare\lib\Materials        # MCsquare /Materials directory
  BDL: BDL_default_UN3_Al_RangeShifter_tilted.txt  # Beam model. Go to MCsquare/BDL directory to check what are the other possible models
  BeamletsBy: MCsquare        # Algorithm used to compute the beamlets: Monte Carlo ('MCsquare')
  RidgeFilter: true           # TRUE = convert the different energy layers into a Conformal Energy Filter shape
  ComputeCEMdose : true     # TRUE = compute the dose distribution through the hedgehog, range shifter and aperture
  ComputeIMPTdose : true     #TRUE = compute the dose distribution for the stnadard IMPT plan
  SaveDoseBeamlets : dcm #save the dose of each beamlet in the reference frame of the CT with aperture: dcm (DICOM format) , sparse (sparse matrix) , false (not saved)
  SaveHighResCT : true     # Do not save the high resolution CT for each beamlet in the reference frame of the beamlet
  SaveHighResDoseMap : true  # Do not save the dose map at CEFDoseGrid resolution in the reference frame of the beamlet
  CEFDoseGrid: [1, 1, 1]      # Size (mm) of final dose scoring grid. Compute the final dose through CEF on a different grid than the high-res CT (defined by 'intrpCTpxlSize')
  makeSTL: true               # TRUE = export the CEF in a STL file for the 3D printer
  exportCEFinCT : false #Export a virtual CT scan containing the CEF
  showGraph: true             # true = display the graphs during computation
  Spike:
    MinThickness :  2         # Minimum thickness (mm) of the base plate of the Conformal Energy Filter filter
    MaterialID : Tusk    #ID of the material used for CEF as defined in MCsquare material list
    SpikeType : fractal     #Aztec pyramid with the centre of the spike corresponds to the BP with smaller range ('up') or the largest range ('down') or 'ellipse' or 'fractal'
    SpikeOrientation : PATIENT_SIDE  # Direction of the spike of the CEM: 'PATIENT_SIDE', 'SOURCE_SIDE'
    NbColumns : 10  #Number of pixel (along one dimension) in one cell for fractal spikes
    PreOptimization : Gaussian #Algorithm to pre optimise spike shape: uniform , Gaussian
    Optimization : none #Objective function for the itereative optimisation of spike shape: none , convolution
    OptMaxIter : 300          # Optimisation convergence criterium. This controls the max number iterations in finding the optimal spike dimension
    intrpCTpxlSize :  0.4     # Size (mm) of the voxels in the interpolated CT used to compute dose through CEF
    Scattering: Moliere # Scattering model used for CEM design. It relates the CEM material thickness to the spot sigma. POssible options are 'SAM', 'Moliere' and 'User'. At fault to define an algorithm, Moliere is used by default.
  Beams:
    name: Beam1               # Beam name
    GantryAngle: 0            # Gantry angle in degrees
    PatientSupportAngle: 0    # Couch rotation angle in degree
    isocenter: []             # in mm, DICOM coords. You can set it manually, or leave empty. By default empty, it will be calculated as the center of the selected target
    SpotAtIso: true           # [OPTIONAL: default = false]. If true, the spot lattice is centered so that there is a spot at isocenter
    TargetMargin: [5, 5, 5]   # Margin around the target to take into account penumbra and setup errors (mm). Used for the definition of the spot positions
    ApertureMargin: [1, 1, 1] # Margin around the target Used for the definition of the aperture contour
    LayerSpacing: 2           # Spacing between energy layers in WET-mm (Water equivalent length). This defines the steps in the Conformal Energy Filter
    SpotSpacing: 15           # Lateral spacing between spots (perpendicular to beam direction) in mm
    NbScarves: 1              # Number of scarves to paint on the BEV
    GridLayout: SQUARE        # Define the layout of the spots: HEXAGONAL (default) or SQUARE
    addPrinterErrors : false  # Type of error to introduce: false , 'dilate' , 'erode' , 'TallSlim','rough'
    ApertureBlock : 1         # 0 = do not use an aperture for this beam 1 = use an aperture for the beam
    AirGap : 0               # Air gap (mm) between skin and aperture block
    SnoutID : flash-UN80      # Snout type
    RSinfo:
      RangeShifterID: RS_Block
  TargetROI: ct_PTV               # name for target ROI
  ExternalROI: ct_BODY            # name for external ROI - the body contour
  optFunction:
  - name: max                # Type of objective function. Possible types are: min, max,max_mean, min_mean, minDVH, maxDVH, minDR (minimum average of the percentile dose rate), minDRm (minimum median of the percentile dose rate), minDADRm (minimum median of the dose averaged dose rate)
    ROIname: ct_PTV          # Name for the ROI to which the objective function needs to be applied
    intersect: ''            # The objective will be applied to "ROIname" intersect with "intersect". Blank if no intersection needed
    remainder: ''            # The objective will be applied to "ROIname" remainder with "remainder". Blank if no remainder needed
    Dref: 8.2                 # Reference dose in Gy
    DRref: 0                 # Not used
    Vref: 0.95               # Reference volume in 1% only needed for minDVH and maxDVH functions
    impw: 0.5                # Importance weight for the current objective function (impw > 0)
    robust: 0                # Set robust to 1 if robustness optimization needs to be applied to this volume, otherwise set to 0
  - name: min                # Type of objective function. Possible types are: min, max,max_mean, min_mean, minDVH, maxDVH, minDR (minimum average of the percentile dose rate), minDRm (minimum median of the percentile dose rate), minDADRm (minimum median of the dose averaged dose rate)
    ROIname: ct_PTV          # Name for the ROI to which the objective function needs to be applied
    intersect: ''            # The objective will be applied to "ROIname" intersect with "intersect". Blank if no intersection needed
    remainder: ''            # The objective will be applied to "ROIname" remainder with "remainder". Blank if no remainder needed
    Dref: 7.8                 # Reference dose in Gy
    DRref: 0                 # Not used
    Vref: 0.95               # Reference volume in 1% only needed for minDVH and maxDVH functions
    impw: 0.5                # Importance weight for the current objective function (impw > 0)
    robust: 0                # Set robust to 1 if robustness optimization needs to be applied to this volume, otherwise set to 0
  - name: minDR              # Type of objective function. Possible types are: min, max,max_mean, min_mean, minDVH, maxDVH, minDR (minimum average of the percentile dose rate), minDRm (minimum median of the percentile dose rate), minDADRm (minimum median of the dose averaged dose rate)
    ROIname: ct_PTV          # Name for the ROI to which the objective function needs to be applied
    intersect: ''            # The objective will be applied to "ROIname" intersect with "intersect". Blank if no intersection needed
    remainder: ''            # The objective will be applied to "ROIname" remainder with "remainder". Blank if no remainder needed
    Dref: 4                  # Dose (Gy / FRACTION) in OAR above which the dose rate condition must be respected
    DRref: 40                # Reference dose rate in Gy/s
    Vref: 0.98               # Not used
    impw: 0.01                # Importance weight for the current objective function (impw > 0)
    robust: 0                # Set robust to 1 if robustness optimization needs to be applied to this volume, otherwise set to 0
  - name: minDR              # Type of objective function. Possible types are: min, max,max_mean, min_mean, minDVH, maxDVH, minDR (minimum average of the percentile dose rate), minDRm (minimum median of the percentile dose rate), minDADRm (minimum median of the dose averaged dose rate)
    ROIname: ct_OAR          # Name for the ROI to which the objective function needs to be applied
    intersect: ''            # The objective will be applied to "ROIname" intersect with "intersect". Blank if no intersection needed
    remainder: ''            # The objective will be applied to "ROIname" remainder with "remainder". Blank if no remainder needed
    Dref: 4                  # Dose (Gy / FRACTION) in OAR above which the dose rate condition must be respected
    DRref: 40                # Reference dose rate in Gy/s
    Vref: 0.98               # Not used
    impw: 0.01                # Importance weight for the current objective function (impw > 0)
    robust: 0                # Set robust to 1 if robustness optimization needs to be applied to this volume, otherwise set to 0
  SystSetUpError: [0, 0, 0, 0, 0, 0]     # Systematic setup error (in mm) for x,y and z DICOM coords (positive and negative directions)
  RandSetUpError:
  - [0, 0, 0]                # Standard deviation for random errors for x,y,z axis (in mm, DICOM coords.)
  RangeError: 0              # Proton range error, implemented as a density perturbation (out of %). Recommended value 3-3.5%
  'Opt4Dmode': 0             # 4D optimization. Set to 1 if ON, set to 0 if OFF
  Opt4D:
    Dir4DCT:
    - []                     # Path phase 1
    - []                     # Path phase 2. You can input as many phases as needed
    DirDeformFields:         # Path to deformation fields (given by REGGUI workflow)
    Num_4D_Phases: 10        # Number of phases in 4DCT. Must coincide with the number of entries in the Dir4DCT list above.
  fractions: 1               # Number of fractions for the treatment. The final spot weights vector will be divided by this number (w_per_fraction). For FLASH, this is the number of fraction PER beam; the total number of fraction is #beam .* |fractions| as one beam is delivered per fraction
  Inozzle: 500               # Nozzle current (nA) during spot delivery
  protonsBeamlet: 5e4        # Number of protons per beamlet. Default 5e4
  protonsFullDose: 1e6       # Number of protons in the full target. Default 1e7
  protonsHighResDose: 5e4    # Number of protons in the dose in high resolution CT


# Optimization parameters------------------------------------------------------
OptConfig:
  max_iter: 50                           # Maximum number of iterations for optimization. Default 200
  'plotTargetDVH': 0                     # Set to 1 if you want to plot the DVH for the target every few iterations (set to 25 iterations but can be changed in NLPSolver.m). Set to 0 otherwise.
  'plotObjective': 0                     # Set 1 if you want to plot the objective function evolution.
  BeamletsMatrixPrecision: d             # Precision for beamlet matrix. Set 'f' for float or 'd' for double. Default value is 'f' since it reduces the memory. NOTE that for MATLAB v2015 the 'f' option is not working due to the mex file functions are not supported anymore
  mixedOptimization:                     # Mixed optimization ON/OFF, MC_corrections, iter
    'ON': 0                              # Mixed optimization ON if 1, OFF if 0
    MC_corrections: 3                    # Number of MC updates for correction matrix C
    iter: 250                            # Number of iterations after the MC update
    RandSetUpError:
    - [0, 0, 0]                          # Include random errors. In mm
    Opt4D:                               # Include 4D data
       mode: 0                           # 1 - yes include. 0 - no don't include
       Dir4DCT:                          # Paths for the 4DCT phases in mixedoptimization
       - []                              # Path phase 1
       - []                              # Path phase 2. You can input as many phases as needed
       DirDeformFields:                  # Path to deformation fields (given by REGGUI workflow)
       - []                              # Path to deformation fields
       Num_4D_Phases: 5                  # Number of phases in 4DCT. Must coincide with the number of entries in the Dir4DCT list above.


# Output parameters------------------------------------------------------------
Outputs:
  Compute_preForwardDVHs: 0              # Computes DVH for final dose as BeamletMatrix*weights, before performing a final MC forward dose calculation.
  Compute_MCfinalDose: 0                 # Set to 1 if you want to compute a final MC dose (forward dose) for the nominal case
  Compute_MCDVHbands: 0                  # Set to 1 if you want to compute the final MC dose (forwad dose) for all the scenarios beside the nominal DVH band
  DVH_roiSet: [2, 5, 7]                  # Indicate the ROI indices for which you want to calculate the DVH. If empty, it calculates the DVH for all ROIs in RTSTRUCT.dcm


# Robustness test parameters---------------------------------------------------
Rtest:
  CTpath:                                # Path for the CT to use in the robustness test
  RTSTRUCT:                              # Path for the RSTRUCT to use in the robustness test
  RandSetUpError: [0, 0, 0]              # In mm
  SystSetUpError: [0, 0, 0, 0, 0, 0]     # In mm
  RangeError: 3                          # In %
  Opt4D:                                 # Include 4D data
    mode: 0                              # 1 - yes test. 0 - no don't test
    Num_4D_Phases: 10                    # Number of phases in 4DCT in robustness test
    Dir4DCT:                             # Paths for the 4DCT phases in test
    - []                                 # Path phase 1. You can input as many phases as needed
    DirDeformFields:                     # Deformation fields (given by REGGUI workflow)
    - []
